name: Unit tests 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Ensure test dependencies are installed
      - name: "Run tests with coverage"
        run: |
         pytest -vv --cov=main --cov-report=xml

  
  lint:
    runs-on: "ubuntu-latest"

    permissions:
      contents: read
      issues: write
      statuses: write
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_PYTHON_AUTOFORMAT: true
          

  todos-to-issue:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Convert TODOs to Issues"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_MARKER: "TODO"
